apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - targetPort: 80  # Pod's port
      port: 80        # Service -> pod port 
      nodePort: 30008 # Port exposed from node
  selector:
    matchLabels:
      app: nginx