apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    livenessProbe:
      exec:
        command: ["echo", "Hello World!"]
      initialDelaySeconds: 5 # wait 5s after pod is booted to start the probes
      periodSeconds: 5 # time between each probe