apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  labels:
    app: resource-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"